USE master;
GO

IF DB_ID('BI_DW') IS NOT NULL
BEGIN
    ALTER DATABASE BI_DW SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE BI_DW;
END;
GO

IF DB_ID('BI_Staging') IS NOT NULL
BEGIN
    ALTER DATABASE BI_Staging SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE BI_Staging;
END;
GO

IF DB_ID('BI_OLTP') IS NOT NULL
BEGIN
    ALTER DATABASE BI_OLTP SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE BI_OLTP;
END;
GO

CREATE DATABASE BI_OLTP;
GO

CREATE DATABASE BI_Staging;
GO

CREATE DATABASE BI_DW;
GO

SELECT 
    name AS BaseDatos,
    create_date AS FechaCreacion
FROM sys.databases
WHERE name IN ('BI_OLTP', 'BI_Staging', 'BI_DW')
ORDER BY name;
GO